In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("answers.csv", index_col=0)
# El salario de las personas de Mx se guarda en la columna salarymx y está en pesos.
# Si el valor de salarymx es == 0 es porque son de otro país y su salario está en la columna salaryusd (en dólares).
# Solo vamos a tomar en cuenta los datos de personas en Mx con salario en pesos.
df = df[(df['salarymx'] > 0)]
df["salarymx"].count()

1333

In [3]:
# Agrupamos en base a años de experiencia.
exp = df.groupby("experience")["salarymx"].agg(['median', 'count'])
# Solamente tomamos en cuenta los grupos en los que tenemos por lo menos 5 observaciones
exp = exp[(exp['count'] > 4)]
exp.head()

             median  count
experience
0           12950.0     12
1           10000.0     80
2           18000.0     97
3           25000.0     85
4           28000.0     91

In [4]:
# Importamos lo que necesitamos para generar graficas con Bokeh
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from bokeh.models import ColumnDataSource, HoverTool, NumeralTickFormatter

output_notebook()

In [5]:
# Si usamos directamente el num de observaciones para el tamaño del círculo nos da valores muy altos
# así que calculamos un valor amortiguado y lo asignamos a una nueva columna 'size'.
exp['size'] = round(np.sqrt(exp['count']/2))*3
exp.head()

             median  count  size
experience
0           12950.0     12   6.0
1           10000.0     80  18.0
2           18000.0     97  21.0
3           25000.0     85  21.0
4           28000.0     91  21.0

In [6]:
source = ColumnDataSource(exp)
p = figure(plot_height=400, plot_width=600)
p.circle(x='experience', y='median', source=source, size='size')
p.title.text = 'Salario medio de acuerdo a a la experiencia'
p.xaxis.axis_label = 'Experiencia (años)'
p.yaxis.axis_label = 'Salario bruto mensual (MXN)'
p.yaxis.formatter = NumeralTickFormatter(format='$0 a')

hover = HoverTool()
hover.tooltips=[
    ('Experiencia', '@experience años'),
    ('Observaciones', '@count'),
    ('Salario medio', '@median{$0,0}'),
]

p.add_tools(hover)

show(p)

## Comparación por género

In [7]:
# Agrupamos por experiencia y género
gender = df[(df['experience'] > 0)].groupby(["experience", "gender"])["salarymx"].agg(['median','count'])
# Descartamos grupos con menos de 5 observaciones.
gender = gender[(gender['count'] > 4)]
gender.head()

                    median  count
experience gender
1          hombre  10000.0     59
           mujer   15000.0     19
2          hombre  18500.0     78
           mujer   14600.0     18
3          hombre  25000.0     65

In [8]:
# Groupby deja experience y gender como un multiindex, en lugar de como columnas.
# Así que le damos un reset_index para que los convierta a columnas normales. 
gender = gender.reset_index()
gender.head()

   experience  gender   median  count
0           1  hombre  10000.0     59
1           1   mujer  15000.0     19
2           2  hombre  18500.0     78
3           2   mujer  14600.0     18
4           3  hombre  25000.0     65

In [9]:
# Ahora que gender ya es una columna normal, podemos usarla como referencia para crear una columna de color.
gender['color'] = ['#1f77b4' if x =='hombre' else '#e617e6' for x in gender['gender']] 

# También le agregamos el size amortiguado
gender['size'] = round(np.sqrt(gender['count']/2))*3
gender.head()

   experience  gender   median  count    color  size
0           1  hombre  10000.0     59  #1f77b4  15.0
1           1   mujer  15000.0     19  #e617e6   9.0
2           2  hombre  18500.0     78  #1f77b4  18.0
3           2   mujer  14600.0     18  #e617e6   9.0
4           3  hombre  25000.0     65  #1f77b4  18.0

In [10]:
src = ColumnDataSource(gender)
p = figure(plot_height = 400, plot_width = 600)
p.circle(x='experience', y='median', source=src, size='size', color='color')

p.title.text = 'Comparativo por género'
p.xaxis.axis_label = 'Experiencia (años)'
p.yaxis.axis_label = 'Salario bruto mensual (MXN)'
p.yaxis.formatter = NumeralTickFormatter(format='$0 a')

hover = HoverTool()
hover.tooltips=[
    ('Género', '@gender'),    
    ('Experiencia', '@experience años'),
    ('Observaciones', '@count'),
    ('Salario medio', '@median{$0,0}'),
]

p.add_tools(hover)

show(p)

## Agrupación por ciudad y país

In [11]:
df2 = pd.read_csv("answers.csv", index_col=0)
cities = df2.groupby("city")["salarymx"].agg(['count', 'median'])
cities = cities.reset_index()
cities = cities[(cities["count"]> 10)]
cities = cities[(cities["median"]> 0)]
cities = cities.sort_values(by=['median'], ascending=False)
cities.head(20)

                 city  count  median
92          Monterrey     74   45000
56        Guadalajara    156   45000
187              cdmx     15   45000
24               Cdmx     42   41000
14               CDMX    483   40600
21             Cancún     12   39000
62         Hermosillo     48   39000
96             Mérida     18   38475
29          Chihuahua     11   33000
50   Estado de México     13   31750
94            Morelia     13   31000
35             Colima     29   31000
2      Aguascalientes     22   31000
74               León     19   30000
118         Querétaro     79   30000
167            Toluca     11   30000
168           Torreón     11   29000
115            Puebla     22   20000
175          Veracruz     13   15000
181            Xalapa     29   10000

Hagamos el breakdown por país. Para ello nos basamos en la columna salaryusd.

In [12]:
cities = df2.groupby("country")["salaryusd"].agg(['count', 'median'])
cities = cities.reset_index()
cities = cities[(cities["median"]> 0)]
cities = cities[(cities["country"]!= "Otro")]
cities = cities.sort_values(by=['median'], ascending=False)
cities.head(20)

           country  count   median
7   Estados Unidos     36  10000.0
1           Canada      3   6500.0
6           España      7   3400.0
2            Chile      4   3150.0
4       Costa Rica      2   2500.0
11            Perú      5   2000.0
9           México   1346   1895.0
5          Ecuador     10   1800.0
8        Guatemala      2   1650.0
3         Colombia     20   1450.0
0        Argentina      4    775.0

## Lenguajes

El dilema con los lenguajes es que cada participante puede escoger varios lenguajes (máximo 3) que utiliza. Así que no podemos tener una única variable categórica para lenguaje, sino que tenemos una variable booleana (Y/N) por cada una de las opciones de lenguaje. Si tuvieramos una única variable, simplemente podríamos hacer un groupby y listo, pero al no tenerla, tenemos que "armar" nuestro dataframe.

Vamos a generar una lista donde cada elemento es a su vez una lista con la info de cada lenguaje (nombre del lenguaje, número de observaciones y salario medio). A partir de esa lista de listas generamos un dataframe y continuamos como de costumbre.

In [13]:
# Inicializamos nuestra lista maestra
lang_list = []
# Leemos la lista de lenguajes a partir de un catálogo.
import csv
with open("lang_options.csv") as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        lang_key = "lang_"+row['key']
        # Creamos una lista con el nombre del lenguaje, su num. de observaciones y salario medio, y agregamos dicha lista a nuestra lista maestra.
        lang_list.append([row['name'], df[(df[lang_key]=="Y")]["salarymx"].count(), df[(df[lang_key]=="Y")]["salarymx"].median()])

# Una vez que tenemos la lista maestra completa, creamos un dataframe indicando el nombre de las columnas.
lang_df = pd.DataFrame(lang_list, columns = ['lenguaje', 'count', 'salario'])
# Agregamos una columna de popularidad que se calcule en base a un valor amortiguado del número de observaciones.        
lang_df['popularidad'] = round(np.sqrt(lang_df['count']/2)*2)
lang_df.head(30)

/home/pedrogk/Projects/salarios/notebook/.venv/lib/python3.6/site-packages/pandas/core/ops/__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

       lenguaje  count  salario  popularidad
0          Bash     63  40000.0         11.0
1            C#    189  34000.0         19.0
2         C/C++     28  33000.0          7.0
3         COBOL      7  35000.0          4.0
4          Dart     12  16500.0          5.0
5        Delphi      8  22500.0          4.0
6        Elixir     25  35000.0          7.0
7   Ensamblador      0      NaN          0.0
8            Go     28  43500.0          7.0
9        Groovy     14  62500.0          5.0
10         Java    275  35000.0         23.0
11   JavaScript    437  35000.0         30.0
12       Kotlin     23  32000.0          7.0
13  Objective C      4  35600.0          3.0
14         Perl      9  43000.0          4.0
15          PHP    138  25000.0         17.0
16       PL/SQL    158  34500.0         18.0
17       Python    123  37500.0         16.0
18            R      5  40000.0          3.0
19         Ruby     63  45500.0         11.0
20         Rust      4  55000.0          3.0
21        Scala      9  30000.0          4.0
22        Swift     21  32000.0          6.0
23      VB .NET     38  23500.0          9.0

In [14]:
from bokeh.models import LabelSet
from bokeh.models import Range1d

src = ColumnDataSource(lang_df)
p = figure()
# Ponemos los circulos invisibles pero con tamaño para que sirvan los tooltips en hover.
p.circle(source=src, y='popularidad', x='salario', line_color=None, fill_color=None, size=20)
p.yaxis.axis_label = 'Popularidad'

# La escala de popularidad tiene unidades arbitrarias así que prefiero evitar que se despliegue.
p.yaxis.major_label_text_font_size = '0pt'

p.xaxis.axis_label = 'Salario bruto mensual (MXN)'
p.xaxis.formatter = NumeralTickFormatter(format='$0 a')    
p.x_range = Range1d(10000, 70000)

labels = LabelSet(source=src, x='salario', y='popularidad', text='lenguaje', level='glyph',
              x_offset=-10, y_offset=-5, render_mode='canvas', text_font_size="9pt", text_color='#1f77b4')
p.add_layout(labels)

hover = HoverTool()
hover.tooltips=[
    ('Lenguaje', '@lenguaje'),
    ('Observaciones', '@count'),
    ('Salario medio', '@salario{$0,0}'),
]

p.add_tools(hover)

show(p)

## Inglés

In [15]:
ingles = df.groupby("english_label")["salarymx"].agg(['count', 'median']).sort_values(by=['median'], ascending=False)
ingles

                                                    count  median
english_label
Avanzado: Puedo conversar y escribir sin proble...    287   56000
Nativo o bilingue (ILR 5)                              59   56000
Profesional: Puedo interactuar profesionalmente...    428   40000
Limitado: Me doy a entender pero con errores de...    385   28000
Elemental: Sé lo básico para sobrevivir (ILR 1)       164   25000
Ninguno (ILR 0)                                        10   15000